#!bin/bash
# on my mac computer do "source ./refactored/run" from the repertory TP1_REFACTORING
/usr/bin/env /Users/$USER/.gradle/jdks/eclipse_adoptium-11-aarch64-os_x.2/jdk-11.0.28+6/Contents/Home/bin/java -cp /Users/$USER/Documents/GitHub/GL_SoftwareArchitecture/TPs/TP1_refactoring/refactored/target/classes refactored.Main 